# Generated by Django 4.2.4 on 2023-12-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=9)),
                ('fechaInscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=20)),
                ('horaInscripcion', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
